version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./app:/app

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
