version: '3.8'

services:
  app:
    build: .
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-mistral-large-latest}
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - APP_NAME=${APP_NAME:-AI Blog Creator}
      - VERSION=${VERSION:-1.0.0}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app